name: employee_management
description: An employee management application
environment:
  sdk: '^3.8.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  image_picker: ^0.8.7+3
  flutter_svg: ^2.0.7
  flutter_phoenix: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"